#ifndef INCLUDE_SETTINGS_RENDER_CHESTESP
#/**/define INCLUDE_SETTINGS_RENDER_CHESTESP

#define CHESTESP_RENDER_ONTOP // Render tile entities on top of everything else.
// #define CHESTESP_RENDER_OCCLUSION // Render an occlusion mask for every block where one color is for visible pixels and another color for pixels that are behind a wall.
// #define CHESTESP_RENDER_GLOW // Render a glow outline of tile entities through walls.

#define CHESTESP_RENDER_GLOW_COLOR_BASE COLOR_GOLD // [COLOR_BLACK COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]
#define CHESTESP_GLOW_COLOR_CHEST CHESTESP_RENDER_GLOW_COLOR_BASE // [CHESTESP_RENDER_GLOW_COLOR_BASE COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]
#define CHESTESP_GLOW_COLOR_TRAPPED_CHEST CHESTESP_RENDER_GLOW_COLOR_BASE // [CHESTESP_RENDER_GLOW_COLOR_BASE COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]
#define CHESTESP_GLOW_COLOR_ENDER_CHEST CHESTESP_RENDER_GLOW_COLOR_BASE // [CHESTESP_RENDER_GLOW_COLOR_BASE COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]
#define CHESTESP_GLOW_COLOR_OTHER CHESTESP_RENDER_GLOW_COLOR_BASE // [CHESTESP_RENDER_GLOW_COLOR_BASE COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]

#define CHESTESP_RENDER_OCCLUSION_COLOR_VISIBLE COLOR_LIME // [COLOR_BLACK COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]
#define CHESTESP_RENDER_OCCLUSION_COLOR_OCCLUDED COLOR_RED // [COLOR_BLACK COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]

#endif