#ifndef INCLUDE_SETTINGS_RENDER_ESP
#/**/define INCLUDE_SETTINGS_RENDER_ESP

#include "/enum/color.glsl"

// #define ESP_RENDER_ONTOP // Render entities on top of everything else.
// #define ESP_RENDER_OCCLUSION // Render an occlusion mask for every entity where one color is for visible pixels and another color for pixels that are behind a wall.
#define ESP_RENDER_GLOW // Render a glow outline of entities through walls.

#define ESP_RENDER_GLOW_COLOR_BASE COLOR_GOLD // [COLOR_BLACK COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]
#define ESP_GLOW_COLOR_PEACEFUL ESP_RENDER_GLOW_COLOR_BASE // [ESP_RENDER_GLOW_COLOR_BASE COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]
#define ESP_GLOW_COLOR_NEUTRAL ESP_RENDER_GLOW_COLOR_BASE // [ESP_RENDER_GLOW_COLOR_BASE COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]
#define ESP_GLOW_COLOR_AGRESSIVE ESP_RENDER_GLOW_COLOR_BASE // [ESP_RENDER_GLOW_COLOR_BASE COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]
#define ESP_GLOW_COLOR_DROPS ESP_RENDER_GLOW_COLOR_BASE // [ESP_RENDER_GLOW_COLOR_BASE COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]
#define ESP_GLOW_COLOR_BLOCKS ESP_RENDER_GLOW_COLOR_BASE // [ESP_RENDER_GLOW_COLOR_BASE COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]
#define ESP_GLOW_COLOR_VEHICLES ESP_RENDER_GLOW_COLOR_BASE // [ESP_RENDER_GLOW_COLOR_BASE COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]
#define ESP_GLOW_COLOR_PROJECTILES ESP_RENDER_GLOW_COLOR_BASE // [ESP_RENDER_GLOW_COLOR_BASE COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]
#define ESP_GLOW_COLOR_PLAYERS ESP_RENDER_GLOW_COLOR_BASE // [ESP_RENDER_GLOW_COLOR_BASE COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]
#define ESP_GLOW_COLOR_IMMOBILE ESP_RENDER_GLOW_COLOR_BASE // [ESP_RENDER_GLOW_COLOR_BASE COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]
#define ESP_GLOW_COLOR_OTHER ESP_RENDER_GLOW_COLOR_BASE // [ESP_RENDER_GLOW_COLOR_BASE COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]

#define ESP_RENDER_OCCLUSION_COLOR_VISIBLE COLOR_LIME // [COLOR_BLACK COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]
#define ESP_RENDER_OCCLUSION_COLOR_OCCLUDED COLOR_RED // [COLOR_BLACK COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]

#endif