#ifndef INCLUDE_SETTINGS_RENDER_XRAY
#/**/define INCLUDE_SETTINGS_RENDER_XRAY

#include "/enum/color.glsl"

#define XRAY_RENDER_ONTOP // Render blocks on top of everything else.
// #define XRAY_RENDER_OCCLUSION // Render an occlusion mask for every block where one color is for visible pixels and another color for pixels that are behind a wall.
// #define XRAY_RENDER_GLOW // Render a glow outline of blocks through walls.

#define XRAY_RENDER_GLOW_COLOR_BASE COLOR_GOLD // [COLOR_BLACK COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]
#define XRAY_GLOW_COLOR_MINECRAFT XRAY_RENDER_GLOW_COLOR_BASE // [XRAY_RENDER_GLOW_COLOR_BASE COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]
#define XRAY_GLOW_COLOR_INDUSTRIAL_CRAFT XRAY_RENDER_GLOW_COLOR_BASE // [XRAY_RENDER_GLOW_COLOR_BASE COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]
#define XRAY_GLOW_COLOR_IMMERSIVE_ENGINEERING XRAY_RENDER_GLOW_COLOR_BASE // [XRAY_RENDER_GLOW_COLOR_BASE COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]
#define XRAY_GLOW_COLOR_MEKANISM XRAY_RENDER_GLOW_COLOR_BASE // [XRAY_RENDER_GLOW_COLOR_BASE COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]
#define XRAY_GLOW_COLOR_DRACONIC_EVOLUTION XRAY_RENDER_GLOW_COLOR_BASE // [XRAY_RENDER_GLOW_COLOR_BASE COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]
#define XRAY_GLOW_COLOR_THERMAL_FOUNDATION XRAY_RENDER_GLOW_COLOR_BASE // [XRAY_RENDER_GLOW_COLOR_BASE COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]
#define XRAY_GLOW_COLOR_BIG_REACTORS XRAY_RENDER_GLOW_COLOR_BASE // [XRAY_RENDER_GLOW_COLOR_BASE COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]
#define XRAY_GLOW_COLOR_FORESTRY XRAY_RENDER_GLOW_COLOR_BASE // [XRAY_RENDER_GLOW_COLOR_BASE COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]
#define XRAY_GLOW_COLOR_TINKERS_CONSTRUCT XRAY_RENDER_GLOW_COLOR_BASE // [XRAY_RENDER_GLOW_COLOR_BASE COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]
#define XRAY_GLOW_COLOR_RAILCRAFT XRAY_RENDER_GLOW_COLOR_BASE // [XRAY_RENDER_GLOW_COLOR_BASE COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]

#define XRAY_RENDER_OCCLUSION_COLOR_VISIBLE COLOR_LIME // [COLOR_BLACK COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]
#define XRAY_RENDER_OCCLUSION_COLOR_OCCLUDED COLOR_RED // [COLOR_BLACK COLOR_NAVY COLOR_GREEN COLOR_TEAL COLOR_MAROON COLOR_PURPLE COLOR_GOLD COLOR_SILVER COLOR_GREY COLOR_INDIGO COLOR_LIME COLOR_AQUA COLOR_RED COLOR_PINK COLOR_YELLOW COLOR_WHITE]

#ifdef XRAY_RENDER_ONTOP
#endif

#endif