#ifndef INCLUDE_ENUM_BLOCK
#/**/define INCLUDE_ENUM_BLOCK

#define BLOCK_MINECRAFT_IRON_ORE						16448
#define BLOCK_MINECRAFT_GOLD_ORE						16452
#define BLOCK_MINECRAFT_DIAMOND_ORE						16456
#define BLOCK_MINECRAFT_COAL_ORE						16460
#define BLOCK_MINECRAFT_EMERALD_ORE						16464
#define BLOCK_MINECRAFT_LAPIS_ORE						16468
#define BLOCK_MINECRAFT_REDSTONE_ORE					16472
#define BLOCK_MINECRAFT_QUARTZ_ORE						16476
#define BLOCK_MINECRAFT_COPPER_ORE						16480

#define BLOCK_INDUSTRIAL_CRAFT_COPPER_ORE				16608
#define BLOCK_INDUSTRIAL_CRAFT_TIN_ORE					16612
#define BLOCK_INDUSTRIAL_CRAFT_URAN_ORE					16512
#define BLOCK_INDUSTRIAL_CRAFT_LEAD_ORE					16616

#define BLOCK_IMMERSIVE_ENGINEERING_COPPER_ORE			16736
#define BLOCK_IMMERSIVE_ENGINEERING_BAUXITE_ORE			16640
#define BLOCK_IMMERSIVE_ENGINEERING_LEAD_ORE			16744
#define BLOCK_IMMERSIVE_ENGINEERING_SILVER_ORE			16748
#define BLOCK_IMMERSIVE_ENGINEERING_NICKEL_ORE			16641

#define BLOCK_MEKANISM_OSMIUM_ORE						16769
#define BLOCK_MEKANISM_COPPER_ORE						16864
#define BLOCK_MEKANISM_TIN_ORE							16868

#define BLOCK_DRACONIC_EVOLUTION_DRACONIUM_ORE			16896

#define BLOCK_THERMAL_FOUNDATION_COPPER_ORE				17120
#define BLOCK_THERMAL_FOUNDATION_TIN_ORE				17124
#define BLOCK_THERMAL_FOUNDATION_SILVER_ORE				17132
#define BLOCK_THERMAL_FOUNDATION_LEAD_ORE				17128
#define BLOCK_THERMAL_FOUNDATION_FERROUS_ORE			17024
#define BLOCK_THERMAL_FOUNDATION_SHINY_ORE				17025
#define BLOCK_THERMAL_FOUNDATION_MANA_INFISED_ORE		17026

#define BLOCK_BIG_REACTORS_YELLORITE_ORE				17152

#define BLOCK_APPLIED_ENERGISTICS_QUARTZ_ORE			17372
#define BLOCK_APPLIED_ENERGISTICS_CHARGED_QUARTZ_ORE	17373

#define BLOCK_BIOMES_O_PLENTY_BIOME_BLOCK_ORE			17408
#define BLOCK_BIOMES_O_PLENTY_ENDER_AMETHYST_ORE		17409
#define BLOCK_BIOMES_O_PLENTY_RUBY_ORE					17410
#define BLOCK_BIOMES_O_PLENTY_PERIDOT_ORE				17411
#define BLOCK_BIOMES_O_PLENTY_TOPAZ_ORE					17412
#define BLOCK_BIOMES_O_PLENTY_TANZANITE_ORE				17413
#define BLOCK_BIOMES_O_PLENTY_MALACHITE_ORE				17414
#define BLOCK_BIOMES_O_PLENTY_SAPPHIRE_ORE				17415
#define BLOCK_BIOMES_O_PLENTY_AMBER_ORE					17416

#define BLOCK_FORESTRY_APATITE_ORE						17536
#define BLOCK_FORESTRY_COPPER_ORE						17632
#define BLOCK_FORESTRY_TIN_ORE							17636

#define BLOCK_TINKERS_CONSTRUCT_COBALT_ORE				17664
#define BLOCK_TINKERS_CONSTRUCT_ARDITE_ORE				17665
#define BLOCK_TINKERS_CONSTRUCT_COPPER_ORE				17760
#define BLOCK_TINKERS_CONSTRUCT_TIN_ORE					17764
#define BLOCK_TINKERS_CONSTRUCT_ALUMINUM_ORE			17776

#define BLOCK_RAILCRAFT_SULFUR_ORE						17792
#define BLOCK_RAILCRAFT_SALTPETER_ORE					17793
#define BLOCK_RAILCRAFT_DARK_DIAMOND_ORE				17864
#define BLOCK_RAILCRAFT_DARK_EMERALD_ORE				17872
#define BLOCK_RAILCRAFT_DARK_LAPIS_LAZULI_ORE			17876
#define BLOCK_RAILCRAFT_FIRESTONE_ORE					17794
#define BLOCK_RAILCRAFT_POOR_IRON_ORE					17856
#define BLOCK_RAILCRAFT_POOR_GOLD_ORE					17860
#define BLOCK_RAILCRAFT_POOR_COPPER_ORE					17888
#define BLOCK_RAILCRAFT_POOR_TIN_ORE					17892
#define BLOCK_RAILCRAFT_POOR_LEAD_ORE					17896

#endif